{% set name = "asdf" %}
{% set version = "2.15.2" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3d07e9f9c04c7bde7aa9675273f177c6a7aef14524c30dc2e124e03898fd3b7

build:
  noarch: python
  number: 0
  entry_points:
    - asdftool = asdf.commands.main:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - asdf-standard >=1.0.1
    - asdf-transform-schemas >=0.3.0
    - asdf-unit-schemas >=0.1.0
    - importlib-metadata >=4.11.4
    - jmespath >=0.6.2
    - numpy >=1.22
    - packaging >=19.0
    - pyyaml >=5.4.1
    - semantic_version >=2.8
    - attrs >=20.1.0
    - jsonschema >=4.8

test:
  requires:
    - pytest >=6.0.0
    - astropy >=5.0.4
    - gwcs >=0.18.3
    - pytest-doctestplus
    - pytest-remotedata
    - pytest-openfiles
    - psutil
    - lz4 >=0.10
    - fsspec[http] >=2022.8.2
  imports:
    - asdf
    - asdf.commands
    - asdf.extern
    - asdf.tags
    - asdf.tags.core
  commands:
    - asdftool --help

about:
  home: http://github.com/asdf-format/asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python implementation of the ASDF Standard
  description: |
    Python library for reading and writing ASDF files. The Advanced Scientific
    Data Format (ASDF) is a next generation interchange format for scientific
    data.
  doc_url: http://asdf.readthedocs.io/
  dev_url: http://github.com/asdf-format/asdf

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - eslavich
    - jhunkeler
    - WilliamJamieson
    - braingram
