{% set name = "asdf" %}
{% set version = "3.4.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a2f0b9de6732a472b4137aa5b59d3c20703e7b70f45ea38c2dcbfc95c6370ef

build:
  noarch: python
  number: 0
  entry_points:
    - asdftool = asdf.commands.main:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - asdf-standard >=1.1.0
    - asdf-transform-schemas >=0.3.0
    - importlib-metadata >=4.11.4
    - jmespath >=0.6.2
    - numpy >=1.22
    - packaging >=19.0
    - pyyaml >=5.4.1
    - semantic_version >=2.8
    - attrs >=22.2.0

test:
  requires:
    - fsspec[http] >=2022.8.2
    - lz4 >=0.10
    - psutil
    - pytest >=8
    - pytest-remotedata
  imports:
    - asdf
    - asdf.commands
    - asdf.tags
    - asdf.tags.core
  commands:
    - asdftool --help

about:
  home: http://github.com/asdf-format/asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python implementation of the ASDF Standard
  description: |
    Python library for reading and writing ASDF files. The Advanced Scientific
    Data Format (ASDF) is a next generation interchange format for scientific
    data.
  doc_url: http://asdf.readthedocs.io/
  dev_url: http://github.com/asdf-format/asdf

extra:
  recipe-maintainers:
    - mwcraig
    - eslavich
    - jhunkeler
    - braingram
    - nden
